name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Echo environment variables
        run: |
          echo "Service ID: ${{ secrets.SERVICE_ID }}"
          echo "Template ID: ${{ secrets.TEMPLATE_ID }}"
          echo "Public Key: ${{ secrets.PUBLIC_KEY }}"

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      NODE_ENV: production
      VITE_SERVICE_ID: ${{ secrets.SERVICE_ID }}
      VITE_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      VITE_PUBLIC_KEY: ${{secrets.PUBLIC_KEY }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          NODE_ENV: production
          VITE_SERVICE_ID: ${{ secrets.SERVICE_ID }}
          VITE_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          VITE_PUBLIC_KEY: ${{secrets.PUBLIC_KEY }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
